services:
  app:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../app:/app/app
      - ../../main.py:/app/main.py
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
 

