services:
  postgres:
    image: postgres:16.2
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../app:/app/app
      - ../../main.py:/app/main.py
    env_file:
      - ../../.env
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    
  migrate:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../app:/app/app
      - ../../migrate.py:/app/migrate.py
    env_file:
      - ../../.env
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    command: python migrate.py
